src/main/java/com/demo/model/Band.java
package com.demo.model;

import java.util.List;
import java.util.Map;

/**
 * Created by dhdaan on 12.06.2017.
 */
public class Band extends Performer {
    private String name;
    private Map<Person, List<DateRange>> persons;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Map<Person, List<DateRange>> getPersons() {
        return persons;
    }

    public void setPersons(Map<Person, List<DateRange>> persons) {
        this.persons = persons;
    }

    public Band(String name, Map<Person, List<DateRange>> persons) {
        this.name = name;
        this.persons = persons;
    }

    public Band(long id, String name, Map<Person, List<DateRange>> persons) {
        this.id = id;
        this.name = name;
        this.persons = persons;
    }

    @Override
    public String toString() {
        return "Band{" +
                "id=" + id +
                ", name='" + name + '\'' +
                '}';
    }

    @Override
    public String getDisplayString() {
        return "Band \"" + name + "\"";
    }
}

src/main/webapp/WEB-INF/views/pages/home.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>

<h2>Тестовое задание для соискателей.</h2>
${person}

<p>Тестовое задание должно быть выполнено используя grails либо java 8 с spring framework (для доступа к БД можно
    использовать jdbc, jdbc template, hibernate template, my batis, any JPA 2 implementation (open jpa, hibernate, top
    link, etc.)).</p>

<p>Предеметная область – сервис для поиска музыкальных композиций, авторов, композиторов, исполнителей, альбомов,
    синглов, сборников. Ниже приводится список обязательных требований, которые нужно учесть в модели данных. Список
    атрибутов таблиц не приводится специально, соискателю нужно создать таблицы самостоятельно</p>
<p>Требования которые нужно учесть.</p>
<ol type="1">
    <li>Музыкальная композиция может быть исполнена разными исполнителями. Абсолютно разными с разные периоды времени,
        либо дуэтом, квартетом и т.д
    </li>
    <li>Каждая музыкальная композиция должна иметь одного композитора и автора текста.</li>
    <li>При этом исполнитель, композитор, автор могут быть одним и тем же человеком</li>
    <li>Музыкальная композиция может выпускаться синглом, либо внутри альбома (список песен одного исполнителя или
        группы), либо в составе сборника (песни разных групп/исполнителей на одном диске)
    </li>
    <li>Исполнитель может быть либо группой, либо как отдельный человек.</li>
    <li>Исполнитель может менять группу, то есть например петь с 1990 по 1995 год в одной группе, а с 1996 по 2000 год в
        другой. Причем даты могут пересекаться, то есть он может петь одновременно в нескольких группах.
    </li>
</ol>
<p>Результат выполнения задания.</p>
<ol type="1">
    <li>Исходные коды, проект собираемый в war gradle.</li>
    <li>ER модель данных.</li>
    <li>Проект при запуске должен создавать в БД тестовые данные, минимум 30 композиций, 6 альбомов (из них два
        сборника), 10 исполнителей, 5 групп, 10 композиторов, 10 авторов
    </li>
    <li>Также данные должны содержать минимум двух исполнителей, которые пели в разных группах.</li>
    <li>Графический интерфейс для поиска по БД:
        <ol type="a">
            <li>Найти всех исполнителей которые исполняли композицию (композиция – drop down view, то есть выбирается из
                списка)
            </li>
            <li>Найти все группы в которых пел заданный исполнитель.</li>
            <li>Найти все альбомы на которых издавалась заданная композиция.</li>
            <li>Найти все композиции заданного композитора</li>
            <li>Найти все композиции заданного автора</li>
            <li>Найти все композиции заданного исполнителя.</li>
        </ol>
</ol>

src/main/webapp/WEB-INF/views/pages/query.jsp
<%@ taglib prefix="tiles" uri="http://tiles.apache.org/tags-tiles" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<h2>${pageTitle}</h2>
<%--<tiles:insertAttribute name="query-content"/>--%>


<form action="${pageContext.request.contextPath}${requestScope['javax.servlet.forward.request_uri']}" method="get">
    <select name="id">
        <c:forEach items="${selectFromList}" var="selectItem">
            <c:set var="val" value="${selectItem.id}"/>
            <c:if test="${not empty selectedType}">
                <c:set var="val" value="${val}_${selectItem['class'].simpleName}"/>
            </c:if>
            <c:set var="sel" value=""/>
            <c:if test="${not empty selectedId && selectedId==selectItem.id}">
                <c:choose>
                    <c:when test="${not empty selectedType}">
                        <c:if test="${selectedType == selectItem['class'].simpleName}">
                            <c:set var="sel" value="selected"/>
                        </c:if>
                    </c:when>
                    <c:otherwise>
                        <c:set var="sel" value="selected"/>
                    </c:otherwise>
                </c:choose>
            </c:if>
            <option value="${val}" ${sel}>${selectItem.displayString}</option>
        </c:forEach>
    </select>
    <input type="submit" value="Go!"/>
</form>
<c:if test="${not empty selectedId}">
    <c:choose>
        <c:when test="${not empty resultList}">
            <c:forEach items="${resultList}" var="resultItem">
                ${resultItem.displayString}<br>
            </c:forEach>
        </c:when>
        <c:otherwise>
            Nothing was found...
        </c:otherwise>
    </c:choose>
</c:if>